version: '3.8'

services:
  backend:
    build:
      context: ./backend-laravel
    volumes:
      - ./backend-laravel:/var/www
    ports:
      - "8000:8000"
    working_dir: /var/www
    command: sh -c "composer install && php artisan key:generate && php artisan serve --host=0.0.0.0 --port=8000"

  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm start"

