name: CI/CD Pipeline

on:
  push:
    branches: [ main, actions ]
  pull_request:
    branches: [ main, actions ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker images
        run: docker compose build

      - name: Levantar servicios
        run: docker compose up -d

      - name: Run backend tests
        run: docker compose exec backend-laravel php artisan test || true

      - name: Run frontend tests
        run: docker compose exec frontend npm test || true

      - name: Upload React build as artifact
        uses: actions/upload-artifact@v4
        with:
          name: react-build
          path: frontend/build

      - name: Upload Laravel logs as artifact
        uses: actions/upload-artifact@v4
        with:
          name: laravel-logs
          path: backend-laravel/storage/logs 

      - name: Login to GitHub Container Registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Tag Docker images
        run: |
          docker tag adesso-project_backend ghcr.io/danieeljp/adesso-erasmus-project-backend:latest
          docker tag adesso-project_frontend ghcr.io/danieeljp/adesso-erasmus-project-frontend:latest

      - name: Push backend image to GHCR
        run: docker push ghcr.io/danieeljp/adesso-erasmus-project-backend:latest

      - name: Push frontend image to GHCR
        run: docker push ghcr.io/danieeljp/adesso-erasmus-project-frontend:latest 

      - name: List Docker images
        run: docker images 